# Generated by Django 4.2 on 2023-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_is_discount_alter_product_is_exist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('why_our_honey', models.TextField(verbose_name='why_our_honey')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'HomeHeader',
                'verbose_name_plural': 'HomeHeaders',
            },
        ),
        migrations.CreateModel(
            name='Our_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='our_property', verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Our_Property',
                'verbose_name_plural': 'Our_Properties',
            },
        ),
    ]
