# Generated by Django 4.2 on 2023-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
    ]
