# Generated by Django 4.2 on 2023-04-04 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='admin'),
        ),
    ]
