# Generated by Django 4.2 on 2023-04-05 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0002_alter_information_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=50, verbose_name='name')),
                ('logo', models.ImageField(upload_to='site_logo', verbose_name='Logo')),
                ('image', models.ImageField(upload_to='about_image', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
