# Generated by Django 4.2 on 2023-04-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0003_aboutus_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date_modified'),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date_create')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
            },
        ),
    ]
